In [1]:
#インポート(ないならpip installでインストール)
import fitz          #PDF読み込むライブラリ(pip install PyMuPDF)
import pandas as pd  #表を生成するライブラリ(pip install pandas)
import numpy as np   #配列を便利に使えるようになるライブラリ(pip install numpy)
import os
import glob
from pathlib import Path

In [2]:
#関数の戻り値を入れる用のデータフレーム
df = pd.DataFrame()

In [3]:
#全角数字を半角数字にする用のテーブル
zenkaku_table = str.maketrans({
    '１': '1',
    '２': '2',
    '３': '3',
    '４': '4',
    '５': '5',
    '６': '6',
    '７': '7',
    '８': '8',
    '９': '9',
    '０': '0',
})

In [1]:
#売上高を抽出する関数
def get_sale(PDF_name):   
    doc = fitz.open(PDF_name) 
    
    #売上高があるページの取得
    array = np.array(doc.get_toc()) 
    page_sales = array[np.any((array == "１主要な経営指標等の推移") | (array == "1主要な経営指標等の推移"), axis = 1), :]
    page_int = int(page_sales[0,2])
    page = doc[page_int - 1]
    
    #２ページ目にある売上高を含めた表の抽出
    tables = page.find_tables()
    
    #抽出した表から売上高を抽出する
    table_data = np.array(tables[0].extract())
    columns = table_data[0]
    a = table_data[np.any(table_data == "決算年月", axis = 1),:]
    b = np.ravel(a)
    
    for i in range(b.size):  #全角を半角にする
        word = b[i]
        hankaku = word.translate(zenkaku_table)
        b[i] = hankaku
    
    data_rows = table_data[1:]
    df = pd.DataFrame(data_rows, columns = b)
    sales = df[df['決算年月'].str.contains('売上' , na = False)] 
        
    return sales

In [5]:
#売上高だけのデータフレームを作成する関数
def make_dataframe(sales):
    a = pd.DataFrame()
    df = a.append(sales, ignore_index = True)
    return df

In [6]:
#ファイルのパスを取得
def make_file_path_list(dir):
    file_path_list = glob.glob(f'./{dir}/*')
    file_path_list.sort()
    
    return file_path_list

In [7]:
def complate(dir):
    df = pd.DataFrame()
    file_path_list = make_file_path_list(dir)
    for i in range(1,59):
        pdf_name = file_path_list[i]
        sales = get_sale(pdf_name)
        df = pd.concat([df,sales])
        print(i)
        print(pdf_name)
    return df

In [8]:
df = complate('yuho_report')

1
./yuho_report/2023-04-24_E33784.pdf
2
./yuho_report/2023-04-25_E04853.pdf
3
./yuho_report/2023-04-27_E05204.pdf
4
./yuho_report/2023-04-27_E05254.pdf
5
./yuho_report/2023-04-27_E26703.pdf
6
./yuho_report/2023-04-27_E31902.pdf
7
./yuho_report/2023-04-27_E36213.pdf
8
./yuho_report/2023-04-27_E37358.pdf
9
./yuho_report/2023-04-27_E38256.pdf
10
./yuho_report/2023-04-28_E25898.pdf
11
./yuho_report/2023-04-28_E36322.pdf
12
./yuho_report/2023-04-28_E37333.pdf
13
./yuho_report/2023-05-22_E05328.pdf
14
./yuho_report/2023-05-24_E04582.pdf
15
./yuho_report/2023-05-24_E31965.pdf
16
./yuho_report/2023-05-24_E32238.pdf
17
./yuho_report/2023-05-25_E04583.pdf
18
./yuho_report/2023-05-25_E05643.pdf
19
./yuho_report/2023-05-25_E20385.pdf
20
./yuho_report/2023-05-25_E32750.pdf
21
./yuho_report/2023-05-25_E34633.pdf
22
./yuho_report/2023-05-25_E35544.pdf
23
./yuho_report/2023-05-25_E37133.pdf
24
./yuho_report/2023-05-26_E30002.pdf
25
./yuho_report/2023-05-26_E31580.pdf
26
./yuho_report/2023-05-26_E33957.pdf
27
./yuho_report/2023-05-26_E36100.pdf
28
./yuho_report/2023-05-26_E36937.pdf
29
./yuho_report/2023-05-29_E31453.pdf
30
./yuho_report/2023-05-30_E33519.pdf
31
./yuho_report/2023-05-30_E37397.pdf
32
./yuho_report/2023-05-31_E05315.pdf
33
./yuho_report/2023-05-31_E35278.pdf
34
./yuho_report/2023-05-31_E36323.pdf
35
./yuho_report/2023-06-14_E05272.pdf
36
./yuho_report/2023-06-15_E04460.pdf
37
./yuho_report/2023-06-15_E05000.pdf
38
./yuho_report/2023-06-15_E05518.pdf
39
./yuho_report/2023-06-15_E32825.pdf
40
./yuho_report/2023-06-15_E37206.pdf
41
./yuho_report/2023-06-16_E05485.pdf
42
./yuho_report/2023-06-16_E05694.pdf
43
./yuho_report/2023-06-16_E22460.pdf
44
./yuho_report/2023-06-16_E24545.pdf
45
./yuho_report/2023-06-16_E36928.pdf
46
./yuho_report/2023-06-19_E00717.pdf
47
./yuho_report/2023-06-19_E04988.pdf
48
./yuho_report/2023-06-19_E05037.pdf
49
./yuho_report/2023-06-19_E05215.pdf
50
./yuho_report/2023-06-19_E05504.pdf
51
./yuho_report/2023-06-19_E05551.pdf
52
./yuho_report/2023-06-20_E02467.pdf
53
./yuho_report/2023-06-20_E04889.pdf
54
./yuho_report/2023-06-20_E05647.pdf
55
./yuho_report/2023-06-20_E32225.pdf
56
./yuho_report/2023-06-20_E36343.pdf
57
./yuho_report/2023-06-21_E02417.pdf
58
./yuho_report/2023-06-21_E02729.pdf

In [10]:
df

,決算年月,2019年1月,2020年1月,2021年1月,2022年1月,2023年1月,2019年2月,2020年2月,2021年2月,2022年2月,...,2023年3月,平成31年3月,令和2年3月,令和3年3月,令和4年3月,令和5年3月,2020年3月期,2021年3月期,2022年3月期,2023年3月期
1,売上高 （千円）,"49, 810, 774","51, 868, 569","48, 003, 297","45, 220, 567","48, 206, 206",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),"2, 254, 092","2, 426, 749","2, 103, 153","2, 107, 874","2, 007, 240",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,"3, 878, 166","3, 928, 546","2, 650, 178","3, 632, 485","4, 299, 846",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,"5, 283, 572","6, 097, 281","7, 077, 484","7, 616, 747","6, 868, 805",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),―,"3, 742, 984","5, 325, 021","5, 920, 092","6, 007, 080",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),―,―,―,"4, 795, 709","7, 323, 080",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,"1, 217, 500","1, 757, 789","2, 219, 053","2, 640, 880",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,"785, 227","789, 282","1, 075, 505",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,"23, 763, 960","26, 120, 452","26, 729, 396","34, 252, 376","39, 929, 250",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),"2, 446, 830","3, 359, 421","6, 331, 634","6, 519, 896","5, 537, 488",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,"1, 264, 319","2, 359, 209","5, 479, 467","6, 552, 032","6, 607, 710",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,"12, 451, 473","13, 794, 354","14, 481, 536","13, 725, 533",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （百万円）,NaN,NaN,NaN,NaN,NaN,"90, 827","97, 479","52, 434","71, 835",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,"2, 286, 101","2, 891, 311",－,"4, 854, 526",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,"2, 005, 220","2, 454, 361","2, 470, 556","2, 494, 085",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,"4, 066, 040","4, 554, 211","4, 258, 759","4, 817, 559",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,"8, 902, 848","10, 815, 726","8, 499, 614","9, 550, 536",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,"2, 482, 856","3, 088, 542","4, 431, 006","4, 308, 223",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,"2, 299, 255","2, 513, 337","2, 545, 189","2, 566, 735",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,―,―,―,―,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （百万円）,NaN,NaN,NaN,NaN,NaN,"50, 568","65, 860","83, 540","104, 722",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,―,―,―,"10, 920, 831",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,売上収益 （千円）,NaN,NaN,NaN,NaN,NaN,"17, 287, 202","18, 677, 080","18, 285, 444","19, 833, 201",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,"1, 150, 296","1, 517, 668","2, 062, 479","2, 294, 800",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,"1, 083, 754","2, 841, 544","4, 060, 437","4, 354, 845",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,"6, 558, 677","9, 300, 399","11, 144, 704","12, 578, 368",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,"2, 684, 846","2, 122, 272","2, 037, 394","2, 119, 080",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,"1, 259, 075","1, 341, 212","1, 254, 860","1, 372, 800",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,"618, 794","456, 800","245, 497","256, 515",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,"370, 952","485, 984","712, 016","1, 086, 661",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 百万円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"70, 342",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,売上収益 ( 百万円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"1, 672, 377",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"20, 622, 900",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2, 167, 211",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"3, 007, 792",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"24, 253, 875",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"7, 966, 701",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 百万円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"38, 968","42, 645","60, 370","72, 759","78, 417",NaN,NaN,NaN,NaN
1,売上高 ( 百万円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"150, 963",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,売上収益 （百万円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"25, 508","27, 532","30, 579","34, 946"
1,売上高 （百万円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"58, 933",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 千円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"48, 368, 324",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 百万円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"67, 227",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （百万円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"17, 331",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （百万円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"48, 380",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2, 696, 814",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 百万円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"25, 341",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"23, 952, 826",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"10, 347, 679",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"1, 748, 671",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （千円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"3, 741, 454",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 ( 百万円),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"125, 930",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,売上高 （百万円）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"58, 144",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN